alias std='shutdown now'
alias s=neofetch
alias tree='tree -C'
alias n=nvim
alias cl=clear
alias e=exit
alias TEST='ping baidu.com'
alias @=$HOME/tmp/ec
alias git='LANG=en_GB git'
alias ra=ranger
alias venus="java -jar /home/lixiaoqi/Documents/计算机组成原理/CS61C/su20-lab-starter/tools/venus.jar"


# thefuck
eval $(thefuck --alias)

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:/$HOME/bin:/usr/local/bin:$PATH

export EDITOR=nvim

# Path to your oh-my-zsh installation.
export ZSH="/home/lixiaoqi/.oh-my-zsh"

ZSH_THEME="rkj-repos"

VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true

bindkey -v
bindkey -M vicmd "h" vi-insert
bindkey -M vicmd "H" vi-insert-bol
bindkey -M vicmd "l" vi-forward-char
bindkey -M vicmd "j" vi-backward-char
bindkey -M vicmd "L" vi-forward-word
bindkey -M vicmd "J" vi-backward-word

bindkey -M vicmd "i" vi-beginning-of-line
bindkey -M vicmd "k" vi-end-of-line

bindkey -M vicmd "K" down-line-or-history
bindkey -M vicmd "I" up-line-or-history

bindkey -M viins "QQ" vi-cmd-mode



# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="true"
export UPDATE_ZSH_DAYS=7
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-interactive-cd zsh-autosuggestions git glassfish vi-mode emoji zsh-syntax-highlighting)


source $ZSH/oh-my-zsh.sh
export GDM_LANG=en_US.UTF-8
export LANG=en_US.UTF-8

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!

# __conda_setup="$('/home/lixiaoqi/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
    # eval "$__conda_setup"
# else
    # if [ -f "/home/lixiaoqi/anaconda3/etc/profile.d/conda.sh" ]; then
        # . "/home/lixiaoqi/anaconda3/etc/profile.d/conda.sh"
    # else
        # export path="/home/lixiaoqi/anaconda3/bin:$path"
    # fi
# fi
# unset __conda_setup

# <<< conda initialize <<<

