alias 'pit'='pip install --target=/usr/lib/python3.9/site-packages'

alias std='shutdown now'
alias s=neofetch
alias tree='tree -C'
alias cl=clear
alias e=exit
alias TEST='ping baidu.com'
alias @=$HOME/tmp/ec
alias git='LANG=en_GB git'
alias ra=ranger

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:/$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/lixiaoqi/.oh-my-zsh"

ZSH_THEME="rkj-repos"

#bindkey -v 
#bindkey -M vicmd "a' vi-insert
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true


# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="true"
export UPDATE_ZSH_DAYS=2
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git glassfish zsh-interactive-cd vi-mode emoji)


source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8
